---
description: "sensu-hello"
builds:
- platform: "linux"
  arch: "amd64"
  asset_filename: "sensu-hello_1.0_linux_amd64.tar.gz"
  sha_filename: "sensu-hello_1.0_sha512_checksums.txt"
  filter:
  -  "entity.system.os == 'linux'"
  -  "entity.system.arch == 'amd64'"
